# Generated by Django 6.1.2 on 2026-10-08 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_size', models.PositiveIntegerField(help_text='The File Size in Bytes.')),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Inspection'), ('INSPECTED', 'Inspected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SheetInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('detected_headers', models.JSONField(default=list, help_text='List of column headers found in the sheet.')),
                ('is_valid_data_sheet', models.BooleanField(default=True)),
                ('inspection_warnings', models.JSONField(blank=True, default=list)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='d_analysis.upload')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='WARNING', max_length=20)),
                ('sheet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('row_index', models.PositiveIntegerField(blank=True, null=True)),
                ('column_name', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='d_analysis.upload')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='QUEUED', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processor_version', models.CharField(default='1.0.0', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='d_analysis.upload')),
            ],
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.FloatField()),
                ('category', models.CharField(default='General', max_length=100)),
                ('calculation_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='d_analysis.upload')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=255)),
                ('source_header', models.CharField(max_length=255)),
                ('standardized_field', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('mapping_version', models.CharField(default='1.0', max_length=20)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='d_analysis.upload')),
            ],
        ),
    ]
