# Generated by Django 6.1.2 on 2026-10-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetinspection',
            name='header_row_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
