# Generated by Django 6.1.2 on 2026-10-10 07:02

from django.db import migrations, models


def mark_inspected_uploads_completed(apps, schema_editor):
    upload_model = apps.get_model('d_analysis', 'Upload')
    upload_model.objects.using(schema_editor.connection.alias).filter(
        status='INSPECTED'
    ).update(status='COMPLETED')


class Migration(migrations.Migration):

    dependencies = [
        ('d_analysis', '0002_sheetinspection_header_row_index'),
    ]

    operations = [
        migrations.RunPython(mark_inspected_uploads_completed, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=50),
        ),
    ]
